

## load the data
```{r}
job_data <- read.csv("C:/Users/adefisayo.akande/Documents/Personal/second semester/Data_Mining/project/new_project/DMProject2017/filtered_data.csv", header =  TRUE )
head(job_data)
dim(job_data)
str(job_data)


#randomly assign either 0 or 1 to the data column to show if the applicant either likes the job or dislikes it 
job_data$like.dislike <- sample(0:1, size = nrow(job_data), replace = TRUE)

#check the distribution 
table(job_data$like.dislike)

levels(job_data$expert_country)

library(plyr)
count(job_data, 'expert_country')
print(count(job_data, 'project_education'))


#convert education data to numeric
job_data$project_education1 <- as.numeric(factor(job_data$project_education))

summary(job_data$project_education1)


#Merge the two masters column together 

# Plots

par(ask = FALSE, mfrow = c(1,1) )

#Educational qualification ditribution per country
# Expert years of work expreince per country

summary(job_data$project_education)

library(ggplot2)
ggplot(job_data,  aes("Education Dsitribution", fill = project_education) ) +
  geom_bar()

ggplot(job_data) +
  geom_bar( aes(project_education, fill = project_education) )


ggplot(job_data, aes(applied, fill = project_education) ) +
  geom_bar(position = "stack")


ggplot(job_data, aes(expert_work_from_home, fill = project_education) ) +
  geom_bar(position = "dodge")

#expert years of experince 
ggplot(job_data, aes(expert_experience,fill = project_education) ) +
  geom_histogram(binwidth = 3)


#Project experince vs expert experince

plot(job_data$project_experience,job_data$expert_experience )

#plot(job_data$expert_province,job_data$expert_experience )

# Project langauge and exper experince

plot(job_data$project_lang,job_data$expert_experience, xlab = "Language", ylab = "Expert Experince" )


#project experince
ggplot(job_data, aes(project_experience) ) +
  geom_bar()
 

#project experince density plot
ggplot(job_data, aes(expert_experience)) +
  geom_density()


#box plot
ggplot(job_data,
  aes(expert_work_from_home, project_education1 )) +
  geom_point() + geom_boxplot()

plot(job_data$project_education1~job_data$expert_work_from_home, xlab= "expert_work_from_home" ,ylab="project_education1" , main="boxplot")

#disribution count per country
plot(job_data$expert_country, , xlab= "expert_country", ylab= " ", main= "Distribution")


#most spoken langauge
ggplot(job_data) +
  geom_bar( aes(expert_country, fill = project_lang) )

ggplot(job_data) +
  geom_bar( aes(project_country, fill = project_education) ) 

################################################################

#ggplot(job_data,aes(job_data$expert_province,job_data$expert_experience ))

ggplot(job_data, aes(expert_experience,expert_country, fill = expert_country))






plot(job_data$applied,job_data$like.dislike )


plot(job_data$project_education,job_data$expert_work_from_home)





plot(job_data$expert_experience, job_data$expert_education1)

barplot(as.matrix(job_data$expert_country), main="Autos", ylab= "Total",
   beside=TRUE, col=rainbow(5))


plot(job_data$expert_experience, job_data$expert_country, xlab= "expert_experience" , ylab= "expert_country", main= "Boxplot")


expert_experience


# using PCA to reduce the observed variables into a smaller number of principal components that will account for most of the variance in the observed variables.

```

  

From our dataset, there so many factors. 


```{r}
par(mfrow=c(1,1))
library(ggplot2)

ggplot(job_data, aes(expert_country,expert_title, colour = project_education)) +
geom_point()+ geom_line() 


plot(expert_country,project_education , data =job_data)

ggplot(job_data, aes(expert_country,project_education, colour = project_education)) +
geom_point()+ geom_line() 


ggplot(job_data, aes(expert_title,like.dislike, colour = expert_country)) +
geom_point()+ geom_line() 




ggplot(job_data, aes(project_education,like.dislike)) +
geom_point()+ geom_line() 






```

